# Generated by Django 5.2.10 on 2026-01-31 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the device (from OwnTracks 'tid' field)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name for the device",
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this device was first registered",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time location data was received from this device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude in decimal degrees (-90 to +90)",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude in decimal degrees (-180 to +180)",
                        max_digits=9,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Unix timestamp when location was recorded (from 'tst' field)",
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="Accuracy of location in meters (from 'acc' field)",
                        null=True,
                    ),
                ),
                (
                    "altitude",
                    models.IntegerField(
                        blank=True,
                        help_text="Altitude above sea level in meters (from 'alt' field)",
                        null=True,
                    ),
                ),
                (
                    "velocity",
                    models.IntegerField(
                        blank=True,
                        help_text="Velocity/speed in km/h (from 'vel' field)",
                        null=True,
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery percentage 0-100 (from 'batt' field)",
                        null=True,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        help_text="Connection type (from 'conn' field): w=WiFi, o=Offline, m=Mobile",
                        max_length=1,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the server received this location data",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device that reported this location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="my_tracks_loc_device__911dfb_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="my_tracks_loc_timesta_58747d_idx"
                    ),
                ],
            },
        ),
    ]
