# Generated by Django 5.2.10 on 2026-01-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the client that submitted this location",
                null=True,
            ),
        ),
    ]
