# Generated by Django 5.2.10 on 2026-01-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0002_location_ip_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnTracksMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of OwnTracks message (status, lwt, transition, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Complete message payload as JSON"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that submitted this message",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the server received this message",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The device that sent this message (if identifiable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "OwnTracks Message",
                "verbose_name_plural": "OwnTracks Messages",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-received_at"],
                        name="my_tracks_own_device__3540c2_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-received_at"],
                        name="my_tracks_own_message_a19512_idx",
                    ),
                ],
            },
        ),
    ]
