# Generated by Django 5.2.10 on 2026-01-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0003_owntracksmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Latitude in decimal degrees (-90 to +90)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Longitude in decimal degrees (-180 to +180)",
                max_digits=10,
            ),
        ),
    ]
