# Generated by Django 5.2.10 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0004_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="tracker_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OwnTracks tracker ID (from 'tid' field)",
                max_length=10,
            ),
        ),
    ]
