# Generated by Django 5.2.10 on 2026-02-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0006_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="location",
            new_name="my_tracks_l_device__a6677d_idx",
            old_name="my_tracks_loc_device__911dfb_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="my_tracks_l_timesta_2f234e_idx",
            old_name="my_tracks_loc_timesta_58747d_idx",
        ),
        migrations.RenameIndex(
            model_name="owntracksmessage",
            new_name="my_tracks_o_device__5862db_idx",
            old_name="my_tracks_own_device__3540c2_idx",
        ),
        migrations.RenameIndex(
            model_name="owntracksmessage",
            new_name="my_tracks_o_message_941b46_idx",
            old_name="my_tracks_own_message_a19512_idx",
        ),
    ]
