# Generated by Django 5.2.10 on 2026-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "my_tracks",
            "0007_rename_my_tracks_loc_device__911dfb_idx_my_tracks_l_device__a6677d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="connection_type",
            field=models.CharField(
                blank=True,
                choices=[("w", "WiFi"), ("o", "Offline"), ("m", "Mobile")],
                help_text="Connection type (from 'conn' field): w=WiFi, o=Offline, m=Mobile",
                max_length=1,
            ),
        ),
    ]
