# Generated by Django 5.2.10 on 2026-02-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0010_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="mqtt_user",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OwnTracks MQTT user (from topic owntracks/{user}/{device})",
                max_length=100,
            ),
        ),
    ]
