# Generated by Django 5.2.10 on 2026-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0011_add_mqtt_user_to_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="CA certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="CA private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the CA certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the CA certificate",
                        max_length=100,
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active CA (only one may be active)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this CA was generated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Authority",
                "verbose_name_plural": "Certificate Authorities",
                "ordering": ["-created_at"],
            },
        ),
    ]
