# Generated by Django 5.2.10 on 2026-02-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0012_add_certificate_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateauthority",
            name="key_size",
            field=models.IntegerField(
                default=4096, help_text="RSA key size in bits (2048, 3072, or 4096)"
            ),
        ),
    ]
