# Generated by Django 5.2.10 on 2026-02-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0013_add_key_size_to_ca"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Server certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="Server private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the server certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the server certificate",
                        max_length=100,
                    ),
                ),
                (
                    "san_entries",
                    models.JSONField(
                        default=list,
                        help_text="Subject Alternative Names (IP addresses and DNS names)",
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active server certificate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this server certificate was generated",
                    ),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this server certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Certificate",
                "verbose_name_plural": "Server Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
