# Generated by Django 5.2.10 on 2026-02-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0014_add_server_certificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Client certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="Client private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name (matches the username)",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the client certificate",
                        max_length=100,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Certificate serial number (hex)", max_length=100
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this certificate is currently active",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this certificate has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this certificate was revoked",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this certificate was issued"
                    ),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this client certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this certificate was issued to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Certificate",
                "verbose_name_plural": "Client Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
