# Generated by Django 5.2.10 on 2026-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_location_tracker_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Latitude in decimal degrees (-90 to +90)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Longitude in decimal degrees (-180 to +180)",
                max_digits=15,
            ),
        ),
    ]
